# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
STRIPE_PUBLISHABLE_KEY: "sk_test_0LdgShGrm0mqlYc9HHeqH24t"
STRIPE_SECRET_KEY: "pk_test_58A1ooWJQI3sBF2Gu8YhhAF1"
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

CLOUDINARY_URL: "cloudinary://541375737187723:gvHsFengZyjI9NmoTjrc2AsufPc@dbg5rmdxj"
