# Add configuration values here, as shown below.
# development:
STRIPE_PUBLISHABLE_KEY: "sk_test_0LdgShGrm0mqlYc9HHeqH24t"
STRIPE_SECRET_KEY: "pk_test_58A1ooWJQI3sBF2Gu8YhhAF1"


CLOUDINARY_URL: "cloudinary://541375737187723:gvHsFengZyjI9NmoTjrc2AsufPc@dbg5rmdxj"
